// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Anime struct {
	ID          int32            `json:"id"`
	Title       string           `json:"title"`
	Description pgtype.Text      `json:"description"`
	Image       pgtype.Text      `json:"image"`
	Type        pgtype.Text      `json:"type"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type AnimeGenre struct {
	ID        int32            `json:"id"`
	AnimeID   int32            `json:"anime_id"`
	GenreID   int32            `json:"genre_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Episode struct {
	ID            int32            `json:"id"`
	EpisodeNumber int32            `json:"episode_number"`
	EpisodeUrl    string           `json:"episode_url"`
	AnimeID       int32            `json:"anime_id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type Genre struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID        int32            `json:"id"`
	Username  string           `json:"username"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
